const ICONS = {
    AppLogo: "/images/AppLogo.svg",
    Collection: "/images/CollectionIcon.svg",
    Cross: "/images/CrossIcon.svg",
    DoDisLike: "/images/DoDisLikeIcon.svg",
    DoLike: "/images/DoLikeIcon.svg",
    History: "/images/HistoryIcon.svg",
    Home: "/images/HomeIcon.svg",
    Like: "/images/LikeIcon.svg",
    MyContent: "/images/MyContentIcon.svg",
    Play: "/images/PlayIcon.svg",
    Save: "/images/SaveIcon.svg",
    Search: "/images/SearchIcon.svg",
    Settings: "/images/SettingsIcon.svg",
    Square: "/images/SquareIcon.svg",
    Subscriber: "/images/SubscriberIcon.svg",
    Subscribe: "/images/SubscribeIcon.svg",
    Support: "/images/SupportIcon.svg",
};
export { ICONS };
